version: '3.7'

networks:
  app_network:

services:
  telegram_bot:
    image: telegram_bot
    restart: always
    depends_on:
      - postgres
#      - ngrok
    environment:
      IP: localhost
      ADMIN: 550676068
      ADMINS: 765135326
      ADMIN1: 1709066039
      BOT_TOKEN: 1808395536:AAE8_x1cSHCXTvfQPmlIf3Q1GzRKjm4TTqI
      DATABASE_URL: postgresql+psycopg2://MMTM_user:MMTM_password@localhost:5434/MMTM_kontrakt
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=MMTM_user
      - POSTGRES_PASSWORD=MMTM_password
      - POSTGRES_DB=MMTM_kontrakt
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data:100M
    networks:
      - app_network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M

#  ngrok:
#    image: ngrok/ngrok:latest
#    restart: unless-stopped
#    command:
#      - "start"
#      - "--all"
#      - "--config"
#      - "/etc/ngrok.yml"
#    volumes:
#      - ./ngrok.yml:/etc/ngrok.yml
#    ports:
#      - 80:80
#    networks:
#      - app_network

#  fastapi:
#    image: telegram_bot
#    ports:
#      - "8000:8000"  # FastAPI port
#    depends_on:
#      - postgres
#    environment:
#      - DATABASE_URL=postgresql+psycopg2://MMTM_user:MMTM_password@localhost:5434/MMTM_kontrakt
#    networks:
#      - app_network
